spring:
  application:
    name: gateway-doctor-appointment
  cloud:
    gateway:
      routes:
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: manager-doctor-appointment
          uri: lb://manager-doctor-appointment
          predicates:
            - Path=/api/manage/**
        - id: manager-appointment-history
          uri: lb://manager-appointment-history
          predicates:
            - Path=/api/history/**
      loadbalancer:
        use404: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080